numPy is a python libray 
50 times faster than list 
numpy stands for numerical python 
numpy and list difference 
why is it faster than list 
numpy is usually imported as np


In [1]:
import numpy as np # to import the numpy
print(np.__version__) #to check the version 

1.26.4


In [ ]:
creating a numpy ndarrry object 

In [5]:
import numpy as np # import numpy
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(np.array))

[1 2 3 4 5 6]
<class 'builtin_function_or_method'>


In [29]:
import numpy as np
arr = np.array((1,2,3,4,5,6))
print(arr)
print(type(arr))
print(arr.ndim) #one dimension 

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1


In [27]:
import numpy as np
arr = np.array(2)
print(arr)
print(type(arr))
print(arr.ndim) #zero dimension 

2
<class 'numpy.ndarray'>
0


In [23]:
#2D array matrix will be created 
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print(arr.ndim) #to check the dimension 

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [25]:
# 3d array  tenser
import numpy as np
arr_id = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[4,5,6]]])
print(arr)
print(arr.ndim)


[[1 2 3]
 [4 5 6]]
2


In [ ]:
import numpy as np
a = np.array([[[1,2,3],[4,5,6],[[1,2,3],[]])

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr[0]) #indexing the 
print(arr[-1]) #acces the last item
print(arr[-2])#similar as we used earlier

1
6
5


In [73]:
#slicing of 1D array 
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr[3:5]) #slicing the elements in the array 
print(arr[-5:-2]) #array[start:end]
print(arr[4:]) #start
print(arr[3:])
print(arr[-3:])
print(arr[1:5:2]) #arr[start:end:step]
print(type(arr))
print(arr.dtype) #to check the data type of the array #int will be displayed 

[4 5]
[2 3 4]
[5 6]
[4 5 6]
[4 5 6]
[2 4]
<class 'numpy.ndarray'>
int32


In [75]:
import numpy as np
arr = np.array(("anurag"))
print(arr.dtype)

<U6


In [81]:
import numpy as np
arr = np.array(['red','blue','megenta','puruple'])
print(arr.dtype)
print(type(arr))
print(arr.ndim)

<U7
<class 'numpy.ndarray'>
1


In [83]:
import numpy as np 
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])
arr3= np.concatenate((arr1,arr2)) #join two array arr1 and arr2 using 
#np.concatenate()
print(arr3)

[1 2 3 4 5 6]


In [85]:
arr1 =np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9])
arr=np.concatenate([arr1,arr2,arr3])
# np.concatenate
print(arr)

[1 2 3 4 5 6 7 8 9]


In [91]:
#Get the shape of an array 
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.ndim)
print(arr)
print(arr.shape) #The shape of an array is the number of elements in each dimension.

2
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [105]:
#Get the shape of an array 
arr = np.array([1,2,3])
print(arr.ndim)
print(arr)
print(arr.shape) #The shape of an array is the number of elements in each dimension.

1
[1 2 3]
(3,)


In [101]:
#Get the shape of an array 
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.ndim)
print(arr)
print(arr.shape) #The shape of an array is the number of elements in each dimension.

2
[[1 2 3 0]
 [5 6 7 8]]
(2, 4)


In [111]:
#reshaping from 1-D to 2-D
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3) 
#4 || columns  
# -- 3 rows 
#multiplication should be the numbers of total elemets in the array ie 4*3 = 12 ie 12 elements should be present in the arry 

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [113]:
#reshaping from 1-D to 2-D
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9]) #9 elements 
newarr = arr.reshape(3,3) #3row and 3 column
#multiplication should be the numbers of total elemets in the array ie 3*3 = 9 ie 9 elements should be present in the arry 

print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [119]:
#reshaping from 1-D to 2-D
import numpy as np
arr = np.array([1,2,3,4,5,6]) #6lements 
newarr = arr.reshape(3,2) #3 colum 2 rows #multiplication should be the numbers of total elemets in the array ie 3*2 = 6 ie 6elements should be present in the arry 
newarr2 = arr.reshape(2,3) #2 columns 3 rows 
print(newarr)
print(newarr2)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [127]:
# mathematical operations using numpy

In [129]:
#range function in array 
import numpy as np
ar_id = np.arange(1,10) #np.arange(start, stop, step)
print(ar_id)

[1 2 3 4 5 6 7 8 9]


In [5]:
arr1 = np.arange(1,10)
arr = arr1.reshape(3,3)
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [145]:
arr1 = np.arange(1,10).reshape(3,3) #we take the range in 1 D and then reshape in  intwo 2D array uing 
arr2 = np.arange(1,10).reshape(3,3)
print(arr2)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [157]:
print(arr1-arr2)
print(arr1+arr2)
print(arr1*arr2)
print(arr1/arr2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Numpay Array Iterating 

In [10]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
for x in arr:
    print(x)

1
2
3
4
5
6


In [18]:
# iterating in 2 D
import numpy as np
arr2 = np.array([[1,2,3,4],[1,2,3,4]]) #2D array 
for x in arr2:
    print(x)

[1 2 3 4]
[1 2 3 4]


In [20]:
#iterating in 3D


In [28]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #in a 3D array it will go through all the 2-D arrays.
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


Spliting Numpy Arrays
array_split()

In [37]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 2) #split the array into the desired number that u gona pass in it np.array_split(arrayname, no)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [47]:
import numpy as np
arr = np.array(["a","b","c","d","e","f"])
newarr = np.array_split(arr, 3) #split into 3 parts 
print(newarr)
print(newarr[0]) #check the index of split array using these
print(newarr[2])


[array(['a', 'b'], dtype='<U1'), array(['c', 'd'], dtype='<U1'), array(['e', 'f'], dtype='<U1')]
['a' 'b']
['e' 'f']


Numpy Searching Arrays
you can search an array for a certain value and return the indexes that get a match
it will return the index value of the element that we want to search


In [64]:
import numpy as np
arr = np.array(["red","yellow","black","red","grey","blue","red"])
x = np.where(arr=='red') #these condition wtil search for the stuff and return the index value
y = np.where(arr=="grey")
print(y)
print(x)

(array([4], dtype=int64),)
(array([0, 3, 6], dtype=int64),)


In [74]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x = np.where(arr%2==0) #these will print the index of all even numbers
y = np.where(arr%2!=0) #these will print the inex of all odd numbes
print(y)
print(x)

(array([ 0,  2,  4,  6,  8, 10], dtype=int64),)
(array([ 1,  3,  5,  7,  9, 11], dtype=int64),)


In [78]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# for x in arr:
#     if(x%2==0):
#         print(x)

Numpy sorting Array


In [81]:
#soring Array
#sorting means putting elements n an ordered sequence 
#Numpy ndarray object has a function called sort(), that will sort a sepecified array
np.sort()

In [83]:
import numpy as np
arr = np.array([3,4,5,33,45,6,7,223,56,1])
print(np.sort(arr)) #in increasing order #ascending 

[  1   3   4   5   6   7  33  45  56 223]


In [85]:
import numpy as np
arr = np.array(["e","z","a","g","m","j"])
print(np.sort(arr))

['a' 'e' 'g' 'j' 'm' 'z']


In [91]:
import numpy as np
arr = np.array([3,4,5,33,45,6,7,223,56,1])
print(np.sort(arr)[::-1]) #for decending 

[223  56  45  33   7   6   5   4   3   1]


getting some elements 
u can filter an array using a boolean indx 

In [111]:
import numpy as np
arr = np.array([41,42,43,44])
filter_arr = arr>42
filter_arr = arr%2==0 #check for even number
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)


[False  True False  True]
[42 44]


In [113]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
filter_arr = arr %2 ==0
newarr = arr[filter_arr]
print(newarr)

[2 4 6]


In [123]:
#creating ndarrays of zeros  nd=ndimensional array
np.ones((5,5)) #(rows,columns) all ones 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [125]:
np.ones((3,2,4)) #3dim 2-rows 4-column

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [141]:
import numpy as np
np.ones((5,5),dtype=int) #specifically get it in the desired data type like here it int in above it was double

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [135]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [137]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [143]:
#creating ndarray 
#creating an identity matrix 
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [153]:
#random int
#create a random inter within the given range
np.random.randint(1,10)

3

In [155]:
np.random.randint(50)

35

In [163]:
np.random.randint(1, 150, 2) #


array([76, 93])

In [171]:
#transpose = convert rows into column and columns into rows
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9]) #9 elements 
newarr = arr.reshape(3,3) #3row and 3 column
print(newarr)
newarr2 = newarr.T
print(newarr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
import numpy as np
arr = np.array([12,12,49,60,40,39])

In [179]:
import numpy as np
np.random.seed(205) #if u want to keep the random generated  numbers common we can the seed() and add a no in it which will be common in all the pc universal 
arr=np.random.randint(1,100,10)
print(arr)

[67 37 57 94 21 17 29 33 64 84]
